### ISSUE TITLE
GeoJson & SQL Server Field Format Issue

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#102]
If a SQL Server Spatial feature includes "image" field, the mapguide-rest will not be able to build a geojson for it. I will hope mapguide-rest will be able to ignore/read image/blob fields.

If a SQL Server Spatial feature includes "bit" field. The mapguide-rest will not show the true/false value in geojson when users are using their custom rest configurations.
1.http://localhost/mapserver20XX/rest/data/test/1234.geojson (No showing bit field value)
2.http://localhost/mapserver20XX/rest/library/Sample/SQL%20Server%20Spatial/data/test.FeatureSource/features.geojson/dbo/QBRoads (Showing bit field value)

**Comment by jumpinjackie** [comment]
Could you provide an example DDL of such a table with several rows of fabricated data?

**Comment by RenoSun** [comment]
1.SQL Server Spatial Table With "image" Data Format Field
I won't be able to give you the test link for the table with image because it will crash the map server. I will have to restart it if you try to link to the SQL Server Table with "image" field.
ID	        int
GEOM	geometry
Photo	image

2.SQL Server Spatial Table With "bit" Data Format Field

a. Not Working
http://maps.qualicumbeach.com/qbmap/rest/data/Roads/100356.geojson
I am not able to load following geojson on Google Map since ONEWAY: with empty value. However, you will be able to see the true/false value. I didn't add "ONEWAY" to my restcfg.json for now, so if you test the link above it won't show up. But if I did add "ONEWAY" in restcfg.json, it will show up like this.

{ "type": "FeatureCollection", "features": [
{ "type": "Feature", "geometry": { "type": "LineString", "coordinates": [[-124.45129073205, 49.352559280644],[-124.45270430036, 49.352568071878]] }, "properties": {"QBID": 100356,"ONEWAY": ,"DISPLAYNAME": "CRESCENT RD W","OCPCATEGORY": "Major Collector","CAPTUREDATE": "TIMESTAMP '2009-11-26 00:00:00'","CAPTUREMETHOD": "orthophotography","SURFACETYPE": "asphalt","MUNICIPALITY": "Qualicum Beach","SPEEDLIMIT": 50,"AREA": 917.33409864141} }
]}

b. Working
http://maps.qualicumbeach.com/qbmap/rest/library/QualicumBeach/SQL%20Server%20Spatial/data/test.FeatureSource/features.geojson/dbo/QBRoads?filter=QBID%20IN%20(100358,100357,100356)

**Comment by jumpinjackie** [comment]
There is an issue with the FDO provider where it crashes when querying from a SQL Server table with an image column. That issue is beyond the scope of mapguide-rest. However, the bit column issue should be fixed now

**Comment by jumpinjackie** [comment]
Ticket reference for the image column issue: https://trac.osgeo.org/fdo/ticket/927

**Comment by jumpinjackie** [comment]
As a workaround, if you want to show the table as GeoJSON but without the image columns crashing the map server, just explicitly specify the properties in the GeoJSON representation configuration (excluding the image properties)
