### ISSUE TITLE
Reminder - Enhanced Feature

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#104]
Question #1

http://osgeo-org.1560.x6.nabble.com/Mapguide-rest-query-restriction-and-runtime-map-questions-td5193319.html#a5193419

**Comment by jumpinjackie** [comment]
Given my current schedule and priorities, I will only be implementing the feature source whitelisting feature as part of #8 for mapguide-rest 1.0

You'll have to use dedicated restcfg.json files for the other features

**Comment by RenoSun** [comment]
Sounds good!

**Comment by jumpinjackie** [comment]
The whitelisting feature has landed and will be available in the next RC
