### ISSUE TITLE
BBOX filter and Coordinate Transformation not using the same coordinate system

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#106]
It will be a good feature if the mapguide-rest allow users to do spatial query using BBOX with transformed coordinates if they are using transformto URL parameters.

For example, the feature originally is in UTM84-10N coordinate system.

No Result
http://localhost/mapguide/rest/library/DatabaseName/FolderName/data/FeatureName.FeatureSource/features.geojson/dbo/Building?transformto=LL84&BBOX=-124.3991,49.35648,-124.3983,49.35709

Working (BBOX using original coordinate system)
http://localhost/mapguide/rest/library/DatabaseName/FolderName/data/FeatureName.FeatureSource/features.geojson/dbo/Building?transformto=LL84&BBOX=390000,5463999,400000,5468999

Thanks!

**Comment by jumpinjackie** [comment]
I would prefer a flag be passed that tells mapguide-rest that the BBOX is in the target coordinate system.

Something like this:

http://localhost/mapguide/rest/library/DatabaseName/FolderName/data/FeatureName.FeatureSource/features.geojson/dbo/Building?transformto=LL84&BBOX=-124.3991,49.35648,-124.3983,49.35709&BBOX_TARGET_CS=1

Which would tell mapguide-rest that BBOX is in LL84

This sound alright?

**Comment by RenoSun** [comment]
Sounds perfect!
Thanks Jackie.
