### ISSUE TITLE
CZML Generation -  HTML Hyperlinks Issue 

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#107]
My tooltips looks like following:
```html
concat('ID: ',   ID   ,'<BR/>'
  ,'<a href="http://localhost/test.aspx?RollNumber=' ,  RollNumber ,'"   target="_blank" >Test Report </a>' )

Then, I inspected the element by using developer tool, and it was shown as following:
<a>Test Report</a>

href or target content are disappear.

Thanks!

**Comment by RenoSun** [comment]
I think it's actually Cesium's issue after I checked the czml.

I will try to figure out why is that.

**Comment by jumpinjackie** [comment]
The last I checked, Cesium sanitizes the HTML content before displaying in the infobox. I recall there being a setting you can use to turn that off.

**Comment by RenoSun** [comment]
This will be my solution :)
viewer.infoBox.viewModel.sanitizer = function (input) {
                    // sanitize input HTML differently, or just return it as-is if you're sure it's safe
                    return input
}
