### ISSUE TITLE
Aggregates Trigger USER/PASSWORD

### ISSUE THREAD

**Issue by mapguideguy** [jumpinjackie/mapguide-rest#114]
http://localhost/mapguide/rest/library/Samples/Sheboygan/Data/Parcels.FeatureSource/aggregates.json/distinctvalues/SHP_Schema/Parcels?property=RTYPE

Trigger User/Password dialog.  
&USERNAME=Anonymous&PASSWORD= does not stop dialog from appearing.

**Comment by jumpinjackie** [comment]
Fixed in 7d82680
