### ISSUE TITLE
Requesting Specific Field From Layer Selection (allow Filtering)

### ISSUE THREAD

**Issue by flipper44** [jumpinjackie/mapguide-rest#117]
When running a GetSelectedFeatures the code does not allow for filtering to just a list of fields in a layer, this can make for very large data packets, especially when connected to unwieldy SQL spatial/Oracle datatables.
Could mapcontroller.php and GetSelectedFeatures function be modified to
$fieldlist = $this->GetRequestParameter("fieldnames", "");
$fieldsToQuery = null;
if ($fieldlist !== "") {
	$fieldsToQuery = new MgStringCollection();
	$fieldnames = explode(",", $fieldlist);
	foreach ($fieldnames as $fieldname) {
		$fieldsToQuery->Add($fieldname);
	}
	$reader = $selection->GetSelectedFeatures($layer, $layer->GetFeatureClassName(), $fieldsToQuery);
}
else{
	$reader = $selection->GetSelectedFeatures($layer, $layer->GetFeatureClassName(), $bMapped);
}

only caveat I found was when requesting geojson and asking for the Unique ID field it would change the fieldname to ID by default
Sometimes databases are hit blindly by things such as zooms and selections where the program would not know such a field name would get renamed in the response
This can be solved in the geojsonwriter.php file by getting rid of the else for if (!$reader->IsNull($i)) {
in the FeatureToGeoJson function.

**Comment by jumpinjackie** [comment]
Regarding the ID field:

The id property is a mandatory part of the GeoJSON spec. If an object is uniquely identifiable, it *must* be designated as the id property in the GeoJSON. Client libraries like OpenLayers operate on this assumption, and fails on GeoJSON features that don't have an "id" property.

**Comment by flipper44** [comment]
That's why my code included both the I'd and original field
