### ISSUE TITLE
Have MapController Return Selection Extent in .Selection responses to prevent having to loop through each feature Bounds programattically

### ISSUE THREAD

**Issue by flipper44** [jumpinjackie/mapguide-rest#119]
In order to get Selection Extents using rest one must loop through every feature bound on every feature and every layer of a request.

**Comment by jumpinjackie** [comment]
This is fixes for 1.0 RC4

GET /session/{session}/{mapName}.Selection/overview.{type}

and include bounds=1 in the query string

**Comment by flipper44** [comment]
Does this require a second call after a selection query? I have a sample of it working without a second call if that would be worth seeing. Won't be able to test this week

**Comment by flipper44** [comment]
Found my Code:
If you pass $featsvc from QueryMapFeatures to CollectQueryMapFeaturesResult
then you can run this at the end of CollectQueryMapFeaturesResult

		$env = $selection->GetExtents($featSvc);
			$ll = $env->GetLowerLeftCoordinate();
			$ur = $env->GetUpperRightCoordinate();
			$bounds = $ll->GetX()." ".$ll->GetY()." ".$ur->GetX()." ".$ur->GetY();
			$xml .= "\n<SelectionExtents>$bounds</SelectionExtents>\n";
        $xml .= "</FeatureInformation>";
        return $xml;

However I believe this may have required me to set $bCanUseNative = false; Is this the reason why you are forcing a second call to have to be run in order to get an extent on an already requested selection? It just seems natural that the return information on a selection query should contain the extent and not force another call. Wouldn't it make more sense having it here?
