### ISSUE TITLE
MapGuide layer integration with Google/OSM

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#121]
Hi Jackie,

I got following exception on my page:

Slim Application Error
The application could not run because of the following error:
Details
Type: mgresourcenotfoundexception
File: C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\app\controller\mappingservicecontroller.php
Line: 468
Trace
#0 C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\app\controller\mappingservicecontroller.php(468): mgmap->create(Object(mgresourceidentifier), 'SheboyganCommer...')
#1 C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\app\routes\v1\routes.services.php(349): MgMappingServiceController->CreateRuntimeMap('json')
#2 [internal function]: {closure}('json')
#3 C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#4 C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#5 C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#6 C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#8 C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\vendor\slim\slim\Slim\Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#9 C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\index.php(198): Slim\Slim->run()
#10 {main}

How can I see more details about what is happening?
Thx!

**Comment by jumpinjackie** [comment]
This simply looks like you're trying to create a runtime map from a Map Definition that doesn't exist

**Comment by RenoSun** [comment]
Yes, you're right Jackie! Thank you :)
