### ISSUE TITLE
sampleapps/vector/ sample tile rendering issue

### ISSUE THREAD

**Issue by AlenKelemen** [jumpinjackie/mapguide-rest#131]
On max zoom ../sampleapps/vector/index.html is not rendering tiles. I tried with some else map definitions - same issue happens. (On windows 7, Mapguide 3.0, rest 1.0 rc4)

![image](https://cloud.githubusercontent.com/assets/8449175/13677561/bba6aa08-e6ea-11e5-860f-48231c9ceb1d.png)

**Comment by AlenKelemen** [comment]
It seems it works OK if all json tiles are cached .

**Comment by jumpinjackie** [comment]
What browser are you using?

**Comment by AlenKelemen** [comment]
Same issue happens with Firefox 40.1 and Chrome Version 48.0. On only one zoom some tiles are missing, when i change zoom level tiles are ok but when i return to previous zoom same tiles disappears again.
There is another but similar issue: I understand that vector tiles are simplified on higher zoom levels, but when zooming in, simplified lines form previous higher zoom level remains visible until all new tiles are rendered. That way line strings appears doubled for some time (see attached image of tiled vector waterworks network layer). Is there a way to control simplification ?

![image](https://cloud.githubusercontent.com/assets/8449175/13781239/f0833dc8-eac2-11e5-9c7f-f2adfe3b381d.png)

**Comment by AlenKelemen** [comment]
Update: issue mentioned here is completely open layers 3 vector tile rendering method, so it has nothing to do with REST.
