### ISSUE TITLE
RuntimeMap does not return Scale Range For Raster Layers

### ISSUE THREAD

**Issue by flipper44** [jumpinjackie/mapguide-rest#132]
Does the Scale Range for Raster Layers have to be gotten in a different manner?

**Comment by jumpinjackie** [comment]
What's the underlying version of your MapGuide Server?

Need to know if it's an issue with the native implementation of CREATERUNTIMEMAP/DESCRIBERUNTIMEMAP (that mapguide-rest passes through if available) or our "emulated" implementation that's used for older MG server versions.

**Comment by flipper44** [comment]
![image](https://cloud.githubusercontent.com/assets/16003063/14149030/c8e4cf42-f667-11e5-9c0e-9076a95f4cdb.png)
This is in 3.0. I have not tested on an older version. This is Utilizing the newest REST release as well, tested on an older copy and same thing.
