### ISSUE TITLE
Runtime Map XYZ Tiled Images

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#139]
I just wonder if there is a way to load XYZ tiles on OL3 or other alternative map APIs by sending session ID with the URL to request the XYZ tiles of the runtime map similar as following URL?

http://localhost/mapguide/rest/session/SESSION_ID/Test.Map/xyz/17/20227/44819/tile.png

However, I know that I have to request  with the map must having a Base Layer Group like following link:
http://localhost/mapguide/rest/library/QualicumBeach/TiledMaps/TiledMap.MapDefinition/xyz/Base%20Layer%20Group/17/20227/44819/tile.png

I think if the users can simply load the runtime map as xyz raster tiles on their web map APIs will be handy!

When the users turn on/off layers, the runtime map xyz tiles will also be updated with the current map setting, and the users will experience smooth xyz tile browsing experience.

However, it might just totally slow down the map browsing experience because the time spend on generate the tiles of the runtime maps. Also, it will use tons of storage space on the server too.

Just an idea.

**Comment by jumpinjackie** [comment]
I don't know what the utility of this is.

Tile URLs generally are long lived and is generally a representation of something that infrequently changes. Session-based maps are the opposite of this. Once the session expires, your XYZ tiles are inaccessbile.

**Comment by RenoSun** [comment]
I think you're right. It's not realistic and necessary to have the XYZ Rumtime map tiles.
