### ISSUE TITLE
GET Features for datetime fields

### ISSUE THREAD

**Issue by AlenKelemen** [jumpinjackie/mapguide-rest#142]
When I use GET feature (http://xxx.FeatureSource/features.geojson/xxx/xxx) for features with TIMESTAMP data it returns json with date string:  "TIMESTAMP '2016-08-20 22:34:52'" 
But when I update feature data with POST I need to have timestamp string formatted like that: "2016-08-20 22:34:52 
 I think it would be more consistent if GET features returns the same string form ("2016-08-20 22:34:52") as string format needed for POST requests. 
(Or is it by design?) 

Also I noticed that GET feature request returns some fractions of the second from date fields which are not really written in the feature source timestamp values, like that: 
"TIMESTAMP '2000-01-01 20:34:02.04601'" while real value is "TIMESTAMP '2000-01-01 20:34:02'" so fractions of the second comes from nowhere ?

**Comment by jumpinjackie** [comment]
It's a bit of laziness on my part. For output, we're just ToString()'ing what comes out of MgDateTime objects we get from the feature reader, which in turn is FDO's string interpretation of the date.

We can definitely tighten up the date format to be just YYYY-MM-DD hh:mm:ss for both date input/output.
