### ISSUE TITLE
Gets the features from the given layer in the selection set (mappedonly=1)

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#154]
I love the fact if I am using mappedonly=1 to request the selection geojson. It only give me the fields that I chose to display to the users.

`GET /session/{session}/{mapName}.Selection/features.{type}/{layerName}?mappedonly=1`

However, it won't give me the geometry of the selection. Is there any way that I can request the mappedonly geojson with geometry content?

Maybe let user use another parameter to choose if they would like to have geometry data included?

`GET /session/{session}/{mapName}.Selection/features.{type}/{layerName}?mappedonly=1&geominclude=1`

**Comment by jumpinjackie** [comment]
Yeah, the `geominclude` would be most preferable
