### ISSUE TITLE
FCGI or Native PHP calls from Rest

### ISSUE THREAD

**Issue by flipper44** [jumpinjackie/mapguide-rest#157]
Jackie,
 I have a hard time following the REST code all the way through a request.
My question is are you  running a FCGI calls, or going Server side directly to the PHP code that the FCGI endpoint would have hit? Because if it is the former, I would imagine that the latter would have much less latency.

**Comment by flipper44** [comment]
Sorry I think I missed the ability to tag as question.  Does Fcgi make a c++ call or PHP?

**Comment by jumpinjackie** [comment]
Yes, mapagent.fcgi makes C++ calls

mapguide-rest is all PHP. The only C++ code it calls is the SWIG-generated wrapper to the MapGuide API. 

Yes PHP is slower than C++, but for that sacrifice in performance we get:

 * Ease of deployment (you just unzip a release package to www/rest)
 * Portability (this works on both Windows and Linux)
 * Flexibility (this covers various versions of MapGuide, where certain APIs don't exist we can "polyfill" the missing bits, eg. QUERYMAPFEATURES/CREATERUNTIMEMAP)
 * Rapid iteration

**Comment by jumpinjackie** [comment]
If you're trying to grok the request process.

It starts at index.php

 * We instantiate a Slim application and its pre-configured routing table (everything under `app/routes`)
 * Slim matches the appropriate route handler based on the URL (the bits after `/mapguide/rest`) and its request parameters
 * That route handler which is a controller method, is invoked.
 * The controller method will then either:
   * Interact with the MapGuide API in some way
   * Use MgHttpRequest/MgHttpResponse to map the RESTful request to a mapagent one and execute that. MgHttpRequest/MgHttpResponse is the same infrastructure the native mapagent uses for handling requests to it. So we get feature-for-feature, bug-for-bug parity with the mapagent for any controller action that takes this path.
 * Either way, the response from either path is then output back to the response stream through Slim's response output APIs (except for reader results, where we do our own chunked output to stream reader content back to the browser)

**Comment by flipper44** [comment]
Thanks,,that clears it up. I wasn't recommending c++, I was just curious how the process works.
