### ISSUE TITLE
Redline Rest Services

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#161]
I was thinking about implement a redlining functionality to our OL3 + MapGuide web GIS.

Then, I checked if mapguide-rest will allow me to send geojson/geometry to our MapGuide/AIMS to create a new layer for redline layer.

Also, the rest services to update the geometry/label information/style of the redline layer, and delete the redline layer.

Please let me know your thoughts, or where should l look into in order to achieve my goal to implement redline feature with OL3 drawing abilities to our AIMS/MapGuide.

Thanks!

**Comment by jumpinjackie** [comment]
You should have a look at the turf.js sample application.

That uses turf.js for creating client-side GeoJSON buffer geometries, but there is code there to send that GeoJSON to the server-side through mapguide-rest APIs to create an equivalent Feature Source and Layer Definition.

**Comment by RenoSun** [comment]
Nice! I will check it out then.

**Comment by RenoSun** [comment]
Hi Jackie,

Is it possible to send a label information for the red line layer feature too?
Where should I look into?
I am using OL3 to draw on the map, and covert the drawing as MapGuide markup layers successfully.
Just want to see if I can allow users to enter some text label of the feature they draw.

Cheers!

**Comment by jumpinjackie** [comment]
You should be able to. The JSON you send up in the turf.js example is the literal JSON form of a LayerDefinition

**Comment by RenoSun** [comment]
Hi Jackie,

It's working very well with following JS code:
`VectorRange =
            {
                "PointTypeStyle": {
                    "DisplayAsText": false,
                    "AllowOverpost": false,
                    "PointRule": [
                        {
                            "LegendLabel": null,
                            "Label": {
                                "Unit": "Points",
                                "SizeContext": "DeviceUnits",
                                "SizeX": "7",
                                "SizeY": "7",
                                "Rotation": "0",
                                "Text": "'" + $('#drawingLabName').val() + "'",
                                "FontName": "Arial",
                                "ForegroundColor": "FF000000",
                                "BackgroundColor": "FFF0FFFF",
                                "BackgroundStyle": "Ghosted"
                            },
                            "PointSymbolization2D": {
                                "Mark": {
                                    "Unit": "Points",
                                    "SizeContext": "DeviceUnits",
                                    "SizeX": "7",
                                    "SizeY": "7",
                                    "Rotation": "0",
                                    "Shape": "Circle",
                                    "Fill": {
                                        "FillPattern": "Solid",
                                        "ForegroundColor": hexOpacity + color,
                                        "BackgroundColor": hexOpacity + color
                                    },
                                    "Edge": {
                                        "LineStyle": "Solid",
                                        "Thickness": "2",
                                        "Color": "ff" + color,
                                        "Unit": "Points"
                                    }
                                }
                            }
                        }
                    ]
                }
            };`

**Comment by jumpinjackie** [comment]
I guess you've got it all figured out. Closing.
