### ISSUE TITLE
Print Restful Service (Enhancement)

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#162]
Hi Jackie,

Is there a way to print the map with mapguide-rest with Legend/North Arrow?

I think it will be beneficial to have a parameter called "legend"/"legendIncluded" with boolean value.

What's your thoughts?
Thanks!

**Comment by RenoSun** [comment]
Hi Jackie,

I tested it out, but nothing it didn't add legend nor remove the scale bar, coords, and north arrow.

http://maps.qualicumbeach.com/qbmap/rest/session/SESSION/MAPNAME.Map/plot.pdf?papersize=A3&orientation=L&pdf_coords=false&pdf_north_arrow=false&pdf_scale_bar=false&pdf_disclaimer=true&pdf_legend=true

![image](https://cloud.githubusercontent.com/assets/5566783/25146369/7bf09050-2428-11e7-9983-ccc90480f7d8.png)

Did I miss anything?

**Comment by jumpinjackie** [comment]
Probably the same reason as re-opening #164 

Works on PHP 5.6, but not 5.3
