### ISSUE TITLE
Redline temporary layers to KML/KMZ

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#164]
Hi Jackie,

Is it possible to use mapguide-rest to download redline layers to KML/KMZ on the fly?

**Comment by RenoSun** [comment]
GET /session/{session}/{resName}.LayerDefinition/kmlfeatures answered my question :)

**Comment by jumpinjackie** [comment]
Okay then :)

**Comment by jumpinjackie** [comment]
In case you missed it, mapguide-rest has a swagger API endpoint listed at `http://servername/mapguide/rest/doc/index.html` where this API and many others are listed

**Comment by RenoSun** [comment]
Hi Jackie,

I am able to download the redline layers as kml on our GIS, but they don't have file extension...

Where should l look into to get the file like kmlfeatures.kml or even name the kml/kmz file with the drawing layer name?

Thank you!

**Comment by jumpinjackie** [comment]
Does adding `downloadname=<filename>` as a query string parameter work?

**Comment by RenoSun** [comment]
Sounds good to me, and with the file extension .Kml/.Kmz too please.

**Comment by jumpinjackie** [comment]
Ok this sounds like a bug then. My previous question was asking for confirmation of something that should be there and not a proposal for a possible solution :)

**Comment by jumpinjackie** [comment]
NOTE: If you grab the latest build from AppVeyor after 2b65de6 is given the A-OK, the API for this route has changed. It is now:

`GET /session/{session}/{resName}.LayerDefinition/kmlfeatures.{type}`

Where `{type}` can be `kml` or `kmz`

To customize the download file name, append `download=1&downloadname=<filename_without_extension>`

**Comment by RenoSun** [comment]
Thank you Jackie!

However, I got following error.

Fatal error: Using $this when not in object context in C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2014\www\rest\app\controller\kmlservicecontroller.php on line 492

If I removed the codes as following, it works.

`//Apply file download parameters if specified
            if ($this->app->request->params("download") === "1" || $this->app->request->params("download") === "true") {
                $param->AddParameter("X-DOWNLOAD-ATTACHMENT", "true");
                if ($this->app->request->params("downloadname")) {
                    $param->AddParameter("X-DOWNLOAD-ATTACHMENT-NAME", $this->app->request->params("downloadname"));
                    $bChunk = false;
                }
            }`

**Comment by jumpinjackie** [comment]
Ok, I might be using constructs that are valid in PHP 5.6 (that I tested this on), but not in PHP 5.3 (that's the version bundled with AIMS 2014?)

**Comment by RenoSun** [comment]
Hi Jackie, 

Yeah, I am still using AIMS2014 with PHP 5.3.8-Win64.

**Comment by RenoSun** [comment]
Tested! and works correctly! Thanks!
