### ISSUE TITLE
Mapguide Rest  - FDO Error

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-rest#169]
hi,
in the config ( restcfg.json) in our application, the FDO source is Oracle. I have tried retrieving the data using the rest config json file as below.

I am not able to get the data. Can you suggest what I am doing wrong.
See my config file:
"Source": {
        "Type": "MapGuide",
        "FeatureSource": "Library://REGEN/DATA/RIICO.FeatureSource",
        "FeatureClass": "RIICO_IA_PLOTS"
    },
    "Representations": {
        "xml": {
            "Adapter": "FeatureSetXml",
            "Methods": {
                "GET": {
                    "PageSize": 100,
                    "MaxCount": 500,
                    "AllowAnonymous": true,
                    "AllowGroups": ["Everyone"]
                }
            }
        },
        "csv": {
            "Adapter": "FeatureSetCsv",
            "Methods": {
                "GET": {
                    "PageSize": 100,
                    "MaxCount": 500,
                    "AllowAnonymous": true,
                    "AllowGroups": ["Everyone"]
                }
            }
        },

The output I am getting is:

"An exception occurred in FDO component.
Error occurred in Feature Source (Library://REGEN/DATA/RIICO.FeatureSource): Unable to find class 'RIICO_IA_PLOTS'  (Cause: , Root Cause: Unable to find class 'RIICO_IA_PLOTS' )"

I have Class/table RIICO_IA_PLOTS in oracle. 

- Sai

**Comment by jumpinjackie** [comment]
If you preview `Library://REGEN/DATA/RIICO.FeatureSource` in the schema report, is `RIICO_IA_PLOTS` visible as a feature class on the sidebar?

Also, you might want to temporarily set `"Error.OutputStackTrace" => true` in `app/config.php` to get more details about the error.

**Comment by saivaradula** [comment]
Thanks for the help Jackie:
I got the result in rest.
-Sai
