### ISSUE TITLE
Generation of PNG without selection

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-rest#170]
Hi Jackie,
The below rest url generates PNG file with the plot ( polygon ) selected ( blue color ). Please see attached image.

URL: http://49.205.113.234/REGEN/rest/data/plots/372455.html

Is it possible to generate PNG file without the selection of the plot or suggest if we can change selection color parameters to be transparent?

![selected_plot_blue](https://cloud.githubusercontent.com/assets/22417624/25613826/4473a70e-2f4d-11e7-9ee3-6c4d95a4c95d.png)
![selected_plot_white](https://cloud.githubusercontent.com/assets/22417624/25613827/447690d6-2f4d-11e7-8e5f-c1383940e4da.png)

Thanks,
- Sai

**Comment by jumpinjackie** [comment]
With this commit (c7a45ee), you can append `selection=0` in the query string to turn off selection

**Comment by saivaradula** [comment]
Hello Jackie:
if selection-0 then, we are getting a blank image. Please suggest the way to 

1. Change the color and transparency for generation of PNG images in REST.  
OR
2. Alternatively, highlight the border without selection. 

Thanks,
 Sai
