### ISSUE TITLE
Rest for non spatial feature source?

### ISSUE THREAD

**Issue by AlenKelemen** [jumpinjackie/mapguide-rest#174]
Is it possible to use feature source Mg rest requests (GET, PUT, POST, DELETE) on non spatial table connected through OSGeo.ODBC ?

**Comment by jumpinjackie** [comment]
If the FDO provider supports insert/update/delete, then yes. Last I checked, it does.

**Comment by AlenKelemen** [comment]
Oh with correct setup, it works. Excellent, thanks.
