### ISSUE TITLE
Is it possible to create new feature source through REST ?

### ISSUE THREAD

**Issue by AlenKelemen** [jumpinjackie/mapguide-rest#175]
Is it possible to create new feature source for existing unmanaged file or data base ?
I refer to the feature source like in the following xml:
```
<?xml version="1.0" encoding="utf-8"?>
<FeatureSource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="FeatureSource-1.0.0.xsd">
  <Provider>OSGeo.SDF</Provider>
  <Parameter>
    <Name>ReadOnly</Name>
    <Value>FALSE</Value>
  </Parameter>
  <Parameter>
    <Name>File</Name>
    <Value>D:\posao\edc\webgis\vodovodOsjek\sdf\vodovodOsijekTest.sdf</Value>
  </Parameter>
</FeatureSource>
```

 I understand that  POST /library/{resourcePath}.FeatureSource/json only creates new sdf/sqlite/shp file.

**Comment by jumpinjackie** [comment]
I think you want:

`POST /library/{resourcePath}/content.xml`

`resourcePath` here includes the resource type (ie. `.FeatureSource`)

**Comment by AlenKelemen** [comment]
Really, that is what i need, thank you.
