### ISSUE TITLE
Are there any ways to accelerate the generation of XYZ tiles?

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-rest#180]
Hi Jackie,

Are there any ways to accelerate the generation of XYZ tiles?

Any possible server configuration or PHP configuration may help?

Thanks

**Comment by jumpinjackie** [comment]
Could you use the new MgTileSeeder tool (https://themapguyde.blogspot.com.au/2017/11/an-introduction-to-mgtileseeder.html) to seed your XYZ tile set?
