### ISSUE TITLE
GET /session/{session}/{resName}.LayerDefinition/features.{type} issue

### ISSUE THREAD

**Issue by AlenKelemen** [jumpinjackie/mapguide-rest#183]
After {session} an additional slash is added by rest code:

![image](https://user-images.githubusercontent.com/8449175/37493269-b52349f4-28a4-11e8-8abd-46a5de4d5e96.png)

**Comment by jumpinjackie** [comment]
But that is a how a session-based resource id is formatted. There is meant to be `//` after the session id.

Are you sure the session wasn't expired?

**Comment by AlenKelemen** [comment]
Maybe I am doing it in wrong way, please check the following:

1. Run Seboygan WebLayout in browser (session is active)
2. Get SessionId (in Chrome developer tools using getSessionId() viewer API)
3.  Copy/paste SessionId and resName (Buildings) in mapguide-rest API Reference under
` GET /session/{session}/{resName}.LayerDefinition/features.{type}` so request is like:
`http://localhost/mapguide/rest/session/8a14f6cc-33f8-11e8-8000-f0d02e3efe7f_en_MTI3LjAuMC4x0AFC0AFB0AFA/Buildings.LayerDefinition/features.geojson`

I get response: Type": "mgresourcenotfoundexception"

**Comment by jumpinjackie** [comment]
Did you copy the Buildings layer into your session repository first? If you haven't, I would expect a `mgresourcenotfoundexception` because when you init a weblayout, the only thing in your session repository when it's created will be a runtime map selection and nothing else.

**Comment by AlenKelemen** [comment]
Thanks for explanation, I get it now...
