### ISSUE TITLE
Send session in POST & PUT requests ?

### ISSUE THREAD

**Issue by AlenKelemen** [jumpinjackie/mapguide-rest#197]
How to send session in POST & PUT requests where body is json feature definition ?
In mapguide-rest API Reference POST & PUT  sets only sessionId in body and (of course) returns 'Malformed JSON body' error.

**Comment by jumpinjackie** [comment]
Do you have an example POST/PUT route?

**Comment by AlenKelemen** [comment]
Just use Mg API reference (../mapguide/rest/doc/index.html#!/library/InsertFeatures) and set session.
You can see that complete body is lost and only session is send.
It occurs only with POST and PUT, DELETE works ok for instrance ..
![image](https://user-images.githubusercontent.com/8449175/69735201-9f7b9400-1130-11ea-9b07-08837b30b104.png)
![image](https://user-images.githubusercontent.com/8449175/69735303-c934bb00-1130-11ea-9633-7bed7d077cba.png)

**Comment by AlenKelemen** [comment]
In my code DELETE looks looks like that:
`fetch(this.url_, {
                method: 'DELETE',
                body: `session=${this.sessionId_}&filter=${filter}`,
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
                }
            })`
So we need to include session in body for POST/PUT...

**Comment by jumpinjackie** [comment]
Ok this is an actual oversight of the API and possibly many others under /library that take POST/PUT requests with XML/JSON bodies. The fact that the swagger docs show a session field in the operation test UI is a case of sloppy copy-pasting of the operation metadata.

I think the easiest fix with the least amount of descriptiveness is to allow passing the session id as a request header of the POST/PUT request and have our relevant controller actions make sure to check the request header for the session id before checking any other places. Then there's the challenge of making sure that we can instruct swagger to make sure that session id field populates as a request header value.

**Comment by jumpinjackie** [comment]
Could you give d1a9e8c45a2a661f6d8792761ffacdfe1577f5c0 a go? I've fixed the swagger metadata for full-body POST/PUT operations to allow passing a session id through a new X-MG-SESSION-ID request header (that the swagger UI should provide a field for)

**Comment by AlenKelemen** [comment]
Works fine... I had to 'add X-Requested-With' to config.php:
`"MapGuide.Cors" => array(
        "origin" => "http://localhost:1234",
        "exposeHeaders" => array("Authorization,Content-Type"),
        "maxAge" => 1728000,
        "allowCredentials" => True,
        "allowMethods" => array("POST, GET, PUT, DELETE, OPTIONS"),
        "allowHeaders" => array("Authorization,Content-Type,X-Requested-With")
    ), `
