### ISSUE TITLE
Ability to Move Sidepanel

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-rest#199]
A request from an end-user ... "can we move the sidebar" ... is this a possible enhancement?

 thanks - Crispin

**Comment by jumpinjackie** [comment]
Did you mean to post this in the mapguide-react-layout repo instead of mapguide-rest? And if so, which particular template are you referring to?

**Comment by Crispin-at-Linknode** [comment]
Ach! Sorry, yes it should have been a "react" ticket/enhancement request.
Specifically for the sidebar layout template

**Comment by jumpinjackie** [comment]
Moved to: https://github.com/jumpinjackie/mapguide-react-layout/issues/1223
