### ISSUE TITLE
Mapguide legend plot only layers visible on map

### ISSUE THREAD

**Issue by noambrand** [jumpinjackie/mapguide-rest#200]
I am a newbie so I hope this topic is posted in the right location.
In Mapguide Open Source GIS website in the quick plot the legend includes all the layers of the map. I want to make a legend that displays only the layers that are visible on map so the legend does not display unnecessary layers. Has this been done already? If not how would you implement this?

**Comment by jumpinjackie** [comment]
You are taking about something that is not related to mapguide-rest at all, so you should've posted this to the mapguide-users mailing list.

On the topic at hand, I do not know what you're talking about. Quick Plot already respects visible layers.

Here's a Quick Plot of Sheboygan zoomed out

![2021-11-02 15_03_16-PlotAsPDF php - Brave](https://user-images.githubusercontent.com/563860/139785325-2540de88-4c92-4161-b029-810cc1dadcb6.png)

And one zoomed in

![2021-11-02 15_03_22-PlotAsPDF php - Brave](https://user-images.githubusercontent.com/563860/139785381-6b1782ba-c468-47de-ac9a-f62b67c6172e.png)

The layers are different in both

**Comment by flipper44** [comment]
When the scale changes based on output size the visible layers will change
asked on the new scale for what you chose to print.
