### ISSUE TITLE
Voting Districts Schema Incorrect in Cesium Example

### ISSUE THREAD

**Issue by mapguideguy** [jumpinjackie/mapguide-rest#209]
In C:\Program Files\OSGeo\MapGuide\Web\www\rest\sampleapps\cesium\index.html

The datasource currently shows:
 districtsSource.load("../../library/Samples/Sheboygan/Data/VotingDistricts.FeatureSource/features.geojson/Default/VotingDistricts?transformto=LL84");

it should replace the "Default" schema with SDF_2_Schema (at least with latest Sheboygan.mgp examples)

 districtsSource.load("../../library/Samples/Sheboygan/Data/VotingDistricts.FeatureSource/features.geojson/SDF_2_Schema /VotingDistricts?transformto=LL84");

**Comment by jumpinjackie** [comment]
You are using an extremely old version of the Sheboygan dataset (`SDF_2_Schema` is a tell-tale sign of a legacy version of this data being converted by MapGuide Studio and that was probably what the very first versions of `Sheboygan.mgp` looked like)

With this baseline: https://download.osgeo.org/mapguide/releases/4.0.0/Beta1/Sheboygan.mgp

The schema for voting distircts is `Default` as expectd.

So I'm gonna close this as wontfix

**Comment by mapguideguy** [comment]
Will reload with newest MGP
________________________________
