### ISSUE TITLE
Data Configurations Do not honour transformTo parameter

### ISSUE THREAD

**Issue by mapguideguy** [jumpinjackie/mapguide-rest#216]
The transformto parameter is not being applied with Data Configurations

for example:

http://localhost/mapguide/rest/data/property/4392.geojson?transformto=WGS84.PseudoMercator

**Comment by jumpinjackie** [comment]
Ok, I figured it out. It honors transformto if specified in the `restcfg.json`, but not if specified from the query string parameter
