### ISSUE TITLE
Error Getting selection geometry

### ISSUE THREAD

**Issue by flipper44** [jumpinjackie/mapguide-rest#220]
Error Getting selection geometry
http://localhost/mapguide/rest/session/c0a94bf0-9849-11ee-8000-7849b77af97f_en_MTI3LjAuMC4x0AFC0AFB0AFA/ElectricMap.Selection/features.geojson/Primary_Lines?transformto=MA83F&properties=ogr_geometry

response: :
{ "type": "FeatureCollection", "features": [
{ "type": "Feature", "geometry": null, "properties": {} }
,{ "type": "Feature", "geometry": null, "properties": {} }
,{ "type": "Feature", "geometry": null, "properties": {} }
,{ "type": "Feature", "geometry": null, "properties": {} }
]}

**Comment by jumpinjackie** [comment]
After following up and personal failure to reproduce, closing as worksforme
