### ISSUE TITLE
&page=1&pagesize=1 Fails with GeoJSON renderer (Release 1.0 RC6)

### ISSUE THREAD

**Issue by mapguideguy** [jumpinjackie/mapguide-rest#223]
For example
/rest/session/1d86c8fe-995a-11ef-8000-7c4c58745c63_en_MTI3LjAuMC4x0AFC0AFB0AFA/Property.Selection/features.geojson/QBParcels?transformto=WGS84.PseudoMercator&pagesize=1&page=1&mappedonly=1&displayproperties=1
Fails,

but...
/rest/session/1d86c8fe-995a-11ef-8000-7c4c58745c63_en_MTI3LjAuMC4x0AFC0AFB0AFA/Property.Selection/features.geojson/QBParcels?transformto=WGS84.PseudoMercator&mappedonly=1&displayproperties=1

Completes...

It seems that C:\Program Files\OSGeo\MapGuide\Web\www\rest\app\util\readerchunkedresult.php
Does not calculate PAGE etc for GEOJSON features.

**Comment by RenoSun** [comment]
Environment MGOS 4 Beta 2 & latest MapGuide-Rest RC6 is currently have this issue that Gordon mentioned, but the same issue doesn't apply to XML or HTML generation.
